version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass reachinbox_redis

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: reachinbox_user
      POSTGRES_PASSWORD: reachinbox_password
      POSTGRES_DB: reachinbox_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  redis_data:
  postgres_data:
  es_data:
